version: '3.8'

services:
  web:
    build:
      context: ./flash
      dockerfile: Dockerfile.prod
    command: gunicorn flash.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/flash/web/website/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/flash/web/website/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
