# Generated by Django 4.2.4 on 2023-08-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='user_rating',
            field=models.CharField(choices=[('happy', '🙂'), ('neutral', '😐'), ('sad', '🙁')], default='neutral', max_length=10),
        ),
    ]
