# Generated by Django 4.2.4 on 2023-09-27 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Count


def fix_migration_0002_errors(apps, schema_editor):
    Card = apps.get_model('website', 'Card')
    Box = apps.get_model('website', 'Box')

    # Krok 1: Połącz karty przypisane do tego samego pudełka
    cards_to_combine = {}

    for card in Card.objects.all():
        if card.box:
            key = (card.user.id, card.box.box_number)
            if key in cards_to_combine:
                cards_to_combine[key].append(card)
            else:
                cards_to_combine[key] = [card]

    for (user_id, box_number), cards in cards_to_combine.items():
        if len(cards) > 1:
            # Połącz karty do jednego pudełka
            box = Box.objects.filter(user__id=user_id, box_number=box_number).first()
            if box:
                for card in cards[1:]:
                    card.box = box
                    card.save()

    empty_boxes = Box.objects.annotate(num_cards=Count('card')).filter(num_cards=0)

    for box in empty_boxes:
        box.delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_box_alter_card_box'),
    ]

    operations = [
        migrations.RunPython(fix_migration_0002_errors),
    ]
